### PR TITLE
Added notes about conda installation and testing for GPU support; Added fix for recent tensorflow libraries

### PR DESCRIPTION
**Pull request by khughitt**
Added notes about conda installation + verifying GPU support in tensorflow.

### CODE REVIEW

**Comment by anishathalye** [comment]
Thanks for the PR.

I'm not sure this installation guide belongs in this repo: the issues with Conda / GPU stuff seem to be generically about Conda, and not specifically to do with the neural-style repo.

**Comment by khughitt** [comment]
Hi @anishathalye,

You are not wrong. The reasons I thought this might be useful are 1) the package no longer works with the current version of SciPy, so something like conda is useful to isolate the installation from the larger system environment, and 2) conda in general is much more widely used today for science/data work, so many people prefer this as an installation method.

If you want I could modify the PR so that the README.md is only updated to include the "conda installation" notes. The GPU support section could then either be moved to a separate file (something like `doc/troubleshooting.md`?), or I could just take it out altogether. Since the PR will still be searchable in the future, anyone encountering similar issues may be able to find it.

If you would prefer to leave out the conda section altogether, I can drop that as well - it's up to you.

The tensorflow work-around really should have been in a separate PR, but it was automatically added to it when I pushed the changes. In any case, I think that bit of code should be useful to include.

Just let me know how you would like to proceed!

**Comment by anishathalye** [comment]
How does this sound:

- send the tensorflow fix in a separate PR and I will merge it
- for the troubleshooting stuff, we can make a page in the wiki with that content, and then add a link to README.md that points to the wiki. this is what I generally do (e.g. as in [here](https://github.com/anishathalye/dotbot#wiki)).

**Comment by khughitt** [comment]
Sounds like a good solution! I'll send a new PR now..

**Comment by khughitt** [comment]
Unrelated, but something that I think would be really interesting / helpful to also include somewhere in the wiki would be any advice you have for working with neural-styles, based on your experience..

There are already some such suggestions in the README.md, but I suspect you have gained many other insights through experimentation over time..

Some things I'm wondering about, for example:

- What makes a good content / style source image?
- For style images, is there a negative impact of having an unrelated "background" to the style of interest (when a photo is used).
- Does it matter what dimensions the style images are?
- etc.

**Comment by anishathalye** [comment]
I think this stuff does matter, and it would be cool to include it in the README.

I don't think I can be the one to do it, though, because I don't really remember 🙃 It's been many years since I experimented heavily with this.

**Pull request closed without merging**
